name: Build OpenPoster

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.head_commit.message, '[build]')
    name: Lint
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: the real deal
        run: |
          for file in ui/*.ui; do
            xmllint --noout "$file" || {
              echo "please kindly check $file thank you"
              exit 1
            }
          done

  build:
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: macos-intel
            os: macos-13
            python: python3
          - name: macos-arm
            os: macos-latest
            python: python3
          - name: windows
            os: windows-latest
            python: python

    name: Build (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          ${{ matrix.config.python }} -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: ${{ matrix.config.python }} compile.py

      - name: Zip (Windows)
        if: matrix.config.name == 'windows'
        run: |
          cd dist
          Compress-Archive -Path OpenPoster -DestinationPath "OpenPoster-${{ matrix.config.name }}.zip"

      - name: Zip (macOS)
        if: matrix.config.name != 'windows'
        shell: bash
        run: |
          cd dist
          zip -r -y "OpenPoster-${{ matrix.config.name }}.zip" OpenPoster.app

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: OpenPoster-${{ matrix.config.name }}
          path: dist/OpenPoster-${{ matrix.config.name }}.zip
